//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace curdoperationsinmvc
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYE
    {
        public int EmployId { get; set; }
        public string EmployName { get; set; }
        public Nullable<decimal> EmploySalary { get; set; }
        public string EmployCity { get; set; }
    }
}
